### ISSUE TITLE
Some things to fix

### ISSUE THREAD

**Issue by AlexGKim** [FutureSurveys/AstroInstitutions#25]
\newcommand{\CNRSA}{CNRS, Laboratoire d'Annecy-le-Vieux de Physique Th\'{e}orique, France}
\newcommand{\EPFL}{Laboratory of Astrophysics, EPFL, 1290 Versoix, Switzerland}
\newcommand{\KASSI}{Korea Astronomy and Space Science Institute, Daejeon 34055, Korea}
\newcommand{\PW}{Participation Worldscope, Sedona, Arizona and Hong Kong, SAR PRC}
\newcommand{\Vanderbilt}{Physics \& Astronomy Department, Vanderbilt University, PMB 401807, 2301 Vanderbilt Place, Nashville, TN 37235}

**Comment by slosar** [comment]
Yes, I fixed these already, but forgot to push. thnx.
